ScoreBoard/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using ScoreBoard.Models;
using ScoreBoard.ViewModels;

namespace ScoreBoard.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ScoreBoard/Controllers/JeuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ScoreBoard.Models;

namespace ScoreBoard.Controllers
{
    public class JeuController : Controller
    {
        private IJeuRepository _jeuRepository;
        private IJoueurRepository _joueurRepository;
        private List<SelectListItem> _selectJoueur;

        public JeuController(IJeuRepository jeuRepository, IJoueurRepository joueurRepository)
        {
            _jeuRepository = jeuRepository;
            _joueurRepository = joueurRepository;
            _selectJoueur = _joueurRepository.ListeJoueurs.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Prenom + ' ' + s.Nom}).ToList();
        }

        public ViewResult Index(int? jeuxId)
        {
            if (jeuxId != null)
            {
                List<Jeu> jeuOfJoueur = _jeuRepository.GetJeuOfJoueur(jeuxId.Value);
                return View(jeuOfJoueur);
            }
            return View(_jeuRepository.ListeJeux);
        }
        [HttpGet]
        public ViewResult Creer(int? jeuxId)
        {
            ViewBag.Joueurs = _selectJoueur;
            ViewBag.jeuxId = jeuxId;
            return View();
        }
        [HttpPost]
        public ActionResult Creer(Jeu jeu)
        {
            jeu.Joueur = _joueurRepository.GetJoueur(jeu.JoueurId);
            _jeuRepository.Ajouter(jeu);

            _joueurRepository.AJourJeu(jeu.JoueurId, jeu);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Jeu jeu = _jeuRepository.GetJeu(id);
            ViewBag.Joueurs = _selectJoueur;
            return View(jeu);
        }
        [HttpPost]
        public ActionResult Modifier(Jeu jeu)
        {
            _jeuRepository.Modifier(jeu);
            return RedirectToAction("Index");
        }

        public ActionResult Supprimer(int id)
        {
            _jeuRepository.Supprimer(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ViewResult Details(int id)
        {
            Jeu jeu = _jeuRepository.GetJeu(id);
                return View(jeu);
        }
    }
}

ScoreBoard/Controllers/JoueurController.cs
using Microsoft.AspNetCore.Mvc;
using ScoreBoard.Models;

namespace ScoreBoard.Controllers
{
    public class JoueurController : Controller
    {
        private readonly IJoueurRepository _joueurRepository;
        public JoueurController(IJoueurRepository joueurRepository)
        {
            this._joueurRepository = joueurRepository;  
        }

        public ViewResult Index()
        {
            return View(_joueurRepository.ListeJoueurs);
        }
        [HttpGet]
        public ActionResult Creer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Creer(Joueur joueur)
        {
            if (ModelState.IsValid)
            {
                _joueurRepository.Ajouter(joueur);
                return RedirectToAction("Index", _joueurRepository);
            }
            else
            {
                return View(joueur);
            }
              
            
            
            
        }
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Joueur joueur = _joueurRepository.GetJoueur(id);
            return View(joueur);
        }
        [HttpPost]
        public ActionResult Modifier(Joueur joueur)
        {
            _joueurRepository.Modifier(joueur);
            return RedirectToAction("Index");
        }
        public ActionResult Supprimer(int id)
        {
            _joueurRepository.Supprimer(id);
            return View();
        }
    }
}

ScoreBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Titre"] - ScoreBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ScoreBoard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">ScoreBoard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Joueur" asp-action="Index">Joueurs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jeu" asp-action="Index">Jeux</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted">
        <div class="container">
            &copy; 2023 - ScoreBoard
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("JQueryValidationScripts", required: false)
</body>
</html>